# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IaouHnlerWZCMpMQZNWrRzU7Tbb-QA8m
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.set_page_config(page_title="TP53 Hotspot Explorer", layout="wide")

st.title("🔬 LLM-assisted TP53 Hotspot Explorer")
st.markdown("""
This dashboard demonstrates a simplified workflow for identifying TP53 mutation hotspots.
It integrates three types of evidence:
- 📚 Literature mentions
- 🌍 Evolutionary conservation
- 🧬 Patient mutation data (COSMIC)
And finally, generates an 📝 AI-style draft summary.
""")

# Load CSVs (make sure these files are in the same folder)
df_lit = pd.read_csv("hotspot_literature_counts.csv")
df_cons = pd.read_csv("conservation_scores.csv")
df_cosmic = pd.read_csv("cosmic_data.csv")
df_combined = pd.read_csv("combined_hotspot_scores.csv")

# Sidebar
st.sidebar.header("Controls")
view = st.sidebar.radio(
    "Choose View",
    ["📚 Literature", "🌍 Conservation", "🧬 Clinical", "📊 Combined", "📝 AI Draft"]
)

# --- Literature ---
if view == "📚 Literature":
    st.subheader("Literature Mentions of TP53 Codons")
    st.dataframe(df_lit)
    fig, ax = plt.subplots()
    df_lit.plot.bar(x="codon", y="mentions", ax=ax)
    st.pyplot(fig)

# --- Conservation ---
elif view == "🌍 Conservation":
    st.subheader("Conservation Scores Across Species")
    st.dataframe(df_cons.head(20))
    fig, ax = plt.subplots()
    df_cons.plot(x="Position", y="DiversityScore", kind="line", ax=ax)
    st.pyplot(fig)

# --- Clinical ---
elif view == "🧬 Clinical":
    st.subheader("COSMIC Mutation Frequencies")
    st.dataframe(df_cosmic.head(20))
    fig, ax = plt.subplots()
    df_cosmic.plot.bar(x="Codon", y="Mutation_Count", ax=ax)
    st.pyplot(fig)

# --- Combined ---
elif view == "📊 Combined":
    st.subheader("Combined Hotspot Evidence")
    st.dataframe(df_combined.head(20))

# --- AI Draft ---
elif view == "📝 AI Draft":
    st.subheader("AI-generated Draft Summary")
    summary = """
    Codons 175, 248, and 273 emerge as strong TP53 hotspots:
    - Frequently mentioned in literature
    - Highly conserved across species
    - Commonly mutated in patient data (COSMIC)

    This demonstrates how combining AI text mining, conservation analysis,
    and clinical datasets yields a simple yet effective hotspot prediction workflow.
    """
    st.info(summary)